### ISSUE TITLE
[Question] Possible to edit a x86 docker image on ARM?

### ISSUE THREAD

**Issue by jwillmer** [multiarch/alpine#36]
I'm trying to use a ARM build pipeline and like to copy my generated application files into an x86 image. Is this possible? I'm asking you since answers to this topic are hard to find on the internet and this project seams to be maintained by some experts. I also created a related [stackoverflow question](https://stackoverflow.com/questions/62592668/build-x86-docker-image-on-arm).

**Comment by lafin** [comment]
In theory, yes. But in this project, only x86_64 can be used as a host system (https://github.com/multiarch/qemu-user-static#supported-host-architectures) to support other architectures, need to add additional support for this to https://github.com/multiarch/qemu-user-static and to this repository.

**Comment by jwillmer** [comment]
Can you give me some details about what needs to happen in order to archive this? I would like to know how far I'm away from a workable solution :)
