### ISSUE TITLE
Missing armhf-v3.5

### ISSUE THREAD

**Issue by rlogiacco** [multiarch/alpine#6]
Alpine 3.5 for arm processor seems missing on Dockerhub

**Comment by lafin** [comment]
@moul please update images in the registry.

**Comment by moul** [comment]
Build in progress

**Comment by moul** [comment]
Pushed :)

**Comment by lafin** [comment]
thank you very much

**Comment by rlogiacco** [comment]
Thanks a million! You might also want to update the latest-stable tag which has not been updated for quite a long time (more than a year).

**Comment by moul** [comment]
@rlogiacco -> https://github.com/multiarch/alpine/pull/14
