### ISSUE TITLE
Question about travis

### ISSUE THREAD

**Issue by lafin** [multiarch/alpine#8]
What do you think about migrate build images to travis? I done some refactoring and now process of build look nice for me. 

fork: https://github.com/lafin/alpine
travis page: https://travis-ci.org/lafin/alpine
docker hub page: https://hub.docker.com/r/lafin/alpine/

**Comment by moul** [comment]
I love it :)

I will cherry-pick your commits and update accordingly with the multiarch namespace

Thanks a lot for this good hack

**Comment by moul** [comment]
Done, it works like a charm, thanks again
